Design Header Footer Composite  Layout
zinza-d2-training/haoth-react pull request #18
Opened 2022-09-05 10:58 UTC by tahuuhao

## Summary

## Dependencies

–

## Testing

2022-09-07 10:01 UTC, hungnp194 requested changes
Lỗi css

![2](https://user-images.githubusercontent.com/61738572/188850929-25b6189a-8183-40d9-980b-239a8be596c5.png)
![1](https://user-images.githubusercontent.com/61738572/188850934-82f50f70-7c2e-40a6-9f5e-5357962dbec8.png)

2022-09-07 10:01 UTC, hungnp194 commented on src/App.css
> +}
Ko viết global overflow-x thế này. Chỗ nào dùng thì viết thôi

2022-09-07 10:01 UTC, hungnp194 commented on src/components/Header/Dropdown.tsx
> +              <Typography sx={{ fontSize: '16px' }}>
Dùng variant thay cho fontSize

2022-09-07 10:01 UTC, hungnp194 commented on src/components/Header/Dropdown.tsx
> +              sx={{ fontSize: '32px !important', color: '#5E35B1 !important' }}
Hạn chế dùng important

2022-09-07 10:01 UTC, hungnp194 commented on src/components/Location/Location.tsx
> +  }, [districtSelect, setValue]);
Khi thay đổi district thì phải reset ward
Thay đổi province thì phải reset district và ward

2022-09-07 11:23 UTC, tahuuhao commented on src/App.css
> +}
@hungnp194 Em tìm mãi mà không thấy thẻ nào gây ra overflow-x

2022-09-08 04:15 UTC, hungnp194 approved these changes

2022-09-08 04:15 UTC, merged